# Setup
title:        "Brandon Trabucco"
tagline:      "For a technologically advanced future, solving complex twenty-first century problems, I research machine learning, and develop computer applications."
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       "Brandon Trabucco"
  url:        https://www.linkedin.com/in/brandontrabucco

# Copyright
copyright:
  year:       "2017"

# Gems
plugins:
  - jekyll-paginate

# Others
markdown: kramdown